apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: jodejs-app
          image: tiasuddin.azurecr.io/nodejs_app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000