apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: jodejs-app
          image: 908198849120.dkr.ecr.ap-south-1.amazonaws.com/devopshint:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000