name: Nodejs Github Action

on: 
  push:
    branches: [ "main" ]
env:
  REGISTRY_NAME: titasuddin
  CLUSTER_NAME: aks-assesment1
  CLUSTER_RESOURCE_GROUP: RG1
  NAMESPACE: default

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 14
            - name: Install kubectl
              uses: azure/setup-kubectl@v3
              with:
                version: 'v1.28.0' # default is latest stable
              id: install

            - name: login to ACR
              uses: azure/docker-login@v1
              with:
                login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
                username: ${{ secrets.REGISTRY_USERNAME }} 
                password: ${{ secrets.REGISTRY_PASSWORD }}