name: Nodejs Github Action

on: 
  push:
    branches: [ "main" ]
env:
  REGISTRY_NAME: titasuddin
  CLUSTER_NAME: aks-assesment1
  CLUSTER_RESOURCE_GROUP: RG1
  NAMESPACE: default
  IMAGE_TAG: latest

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 14
            - name: Install kubectl
              uses: azure/setup-kubectl@v3
              with:
                version: 'v1.28.0' # default is latest stable
              id: install

            - name: login to ACR
              uses: azure/docker-login@v1
              with:
                login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
                username: ${{ secrets.REGISTRY_USERNAME }} 
                password: ${{ secrets.REGISTRY_PASSWORD }}
            - name: build image and push
              run: |
                docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/nodejs_app:${{ env.IMAGE_TAG }}
                docker push ${{ env.REGISTRY_NAME }}.azurecr.io/nodejs_app:${{ env.IMAGE_TAG }}
            - name: set Target AKS cluster
              uses: azure/aks-set-context@v1
              with:
                creds: '${{ secrets.AZURE_CREDENTIALS }}'
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

            # Create imagepullsecret for Azure Container registry (ACR)
            - uses: azure/k8s-create-secret@v1
              with:
                container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
                container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
                container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
                secret-name: registry-connection
                namespace: ${{ env.NAMESPACE }}
            
            
            - name: Deploy
              run: |
                kubectl apply -f deployment.yaml
